name: Theme Store
version: '0.0.4'
slug: theme_store
description: 'A foundation add-on for a community theme store'
url: 'https://example.com/your-repo-or-local'
startup: application
boot: auto
arch:
  - amd64
  - armv7
  - aarch64
init: false
homeassistant_api: true
ingress: false
host_network: false
ports:
  '8080/tcp': 8080
map:
  - config:rw
  - share:rw
schema:
  log_level: list(debug|info|warning|error)?
  api_port: int(1024,65535)?
options:
  log_level: info
  api_port: 8080
