name: Theme Store
version: '0.0.3'
slug: theme_store
description: 'A foundation add-on for a community theme store'
url: 'https://example.com/your-repo-or-local'
startup: application
boot: auto
arch:
  - amd64
  - armv7
  - aarch64
init: false
homeassistant_api: true
ingress: false
host_network: false
ports:
  '8080/tcp': 8080
map:
  - config:rw
  - share:rw
schema:
  log_level: list(info|debug|warning|error)?
options:
  log_level: info
